### ISSUE TITLE
Create a shell-script that test for required kernel features

### ISSUE THREAD

**Issue by marcmo** [esrlabs/northstar#75] opened 2020-08-07 08:07 UTC
relates to  #66
The idea is that Peter will create such a script that actually tries to make use of the required kernel features and reports what is not working.
Once we got this, we can integrate it into the north daemon so it can be executed when the north configuration is set appropriately.

**Comment by pclesr** [comment] 2020-08-11 08:15
Duplicate of https://github.com/esrlabs/northstar/issues/34

**Closed by pclesr** 2020-08-11 08:15 UTC
Labels: linux, portability
